fix: Corrige error de sintanxis
$ mypy cacao_accounting
cacao_accounting\__init__.py:50: error: Name "Talisman" is not defined
[name-defined]

Signed-off-by: William Moreno Reyes <williamjmorenor@gmail.com>

Changes to be committed:
	modified:   cacao_accounting/__init__.py